# Generated by Django 3.0.3 on 2020-05-23 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('genre', models.CharField(choices=[('action', '動作片'), ('romance', '愛情片'), ('drama', '劇情片')], max_length=20)),
                ('release_year', models.IntegerField()),
            ],
        ),
    ]
